name: gulp in docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2

    - name: Docker Run Action
      uses: addnab/docker-run-action@v3
      with:
        image: node:10.14.2-stretch
        run: "npm install && node_modules/.bin/gulp bundle"

    - name: 'Upload Artifact'
    uses: actions/upload-artifact@v2
    with:
      name: ui-bundle.zip
      path: build/ui-bundle.zip
